eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: spring-config-server

server:
  port: 8888

spring:
  application:
    name: spring-config-server

  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zhaoxu77/spring-cloud-config-file/
          search-paths: respo
          username: zhaoxu841020@163.com
          password: zhaoxu625102
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084





