eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: spring-cloud-admin

server:
  port: 8084

spring:
  application:
    name: spring-cloud-admin
  zipkin:
    base-url: http://localhost:9411

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: heath, info

