eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: service-process-zuul

server:
  port: 8769

spring:
  application:
    name: service-process-zuul
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-process-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-process-feign

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"