eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: spring-cloud-zipkin

server:
  port: 9411

spring:
  application:
    name: spring-cloud-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8084

management:
  metrics:
    web:
      server:
        auto-time-requests: false

  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"



