server:
  port: 8763

spring:
  application:
    name: service-prcess
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  #instance:
    #prefer-ip-address: true
    #instance-id: service-prcess62

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"